### ISSUE TITLE
[DOLNOŚLĄSKIE] Lubań Czy jest w bazie?

### ISSUE THREAD

**Issue by kris86k** [szczepienia/szczepienia.github.io#113]
Wiem, że miało nie być pytań o dodanie miast ale od kilku dni próbuję znaleźć termin w Lubaniu i nie znajduje mi tego miasta.
Nie ma go w bazie czy nie ma terminów?

**Comment by szczepienia** [comment]
Zazwyczaj to oznacza, że nie ma najbliższych terminów, ogólnie nie szukam po mniejszych miejscowościach bo zostałem przyblokowany :(
