### ISSUE TITLE
[ŁÓDZKIE] Zły number telefonu do placówki (uuid=1f912bc0-cb3b-42e6-9106-a6907f671e72)

### ISSUE THREAD

**Issue by aleksandersalinski** [szczepienia/szczepienia.github.io#115]
Jestem właścicielem placówki - proszę o zmianę numeru telefonu na 692733446. Pozdrawiam Aleksander Saliński

**Comment by szczepienia** [comment]
Dziękuję, poprawiłem (przepraszam, że tak późno, ale miałem urlop).
