### ISSUE TITLE
Terminy na lipiec

### ISSUE THREAD

**Issue by adiantek** [szczepienia/szczepienia.github.io#118]
Ktoś ma jakieś wycieki i przecieki na temat szczepień w lipcu? Na epacjent gov pl maksymalnie można wybrać datę do 30.06.2021. Próbowałem podmienić request i wymusić na lipiec, ale niestety zwraca pustkę. Na infolinii 989 z tydzień/dwa tygodnie temu dowiedziałem się, że jeszcze kalendarza nie mają, ale nie wiem, nie jest to trochę dziwne ogółem?

**Comment by pjast** [comment]
Dzwoniłam wczoraj - powiedzieli, że "terminy pojawią się mniej więcej tydzień przed 1 lipca, czyli jakoś na dniach". Przez inforlinię terminarz rusza dokładnie tak samo jak przez erejestrację.

**Comment by adiantek** [comment]
ok, dzięki za info :D
