### ISSUE TITLE
Można prosić Chrzanów i Trzebinia

### ISSUE THREAD

**Issue by sylwik7** [szczepienia/szczepienia.github.io#15]
Chrzanów i Trzebinia

**Comment by szczepienia** [comment]
zobacze co da się zrobić, narazie będę ograniczał możliwośc dodawania miejsowości, ze względu na wzost obciążenia serwera (dałe info na głównej stronie)

**Comment by sylwik7** [comment]
Ok dzięki, jakby co oba miasta w Małopolsce. 

Dnia 23 kwietnia 2021 19:34:22 CEST, szczepienia ***@***.***> napisał(a):
>zobacze co da się zrobić, narazie będę ograniczał możliwośc dodawania
>miejsowości, ze względu na wzost obciążenia serwera (dałe info na
>głównej stronie)>
>>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/szczepienia/szczepienia.github.io/issues/15#issuecomment-825810263

--
Wysłane z aplikacji OnetPoczta

**Comment by sylwik7** [comment]
Hej

Jakoś nie mogę zgłosić inaczej. 

W śląskim pojawia się ogrom terminów w Jaworznie w punkcie przy Inwalidów Wojennych. Na infolinii twierdzą, że takiego pkt nie ma w systemie w ogóle. A na telefon podany przy pkt nikt nie odpowiada. W ogóle wygląda jakby ten pkt w Jaworznie jeszcze nie funkcjonował a terminy znikają jak szalone pi kilkadziesiąt dziennie. O co biega? 

Pozdrawiam

Sylwia

Dnia 23 kwietnia 2021 19:34:57 CEST, szczepienia ***@***.***> napisał(a):
>Closed #15.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/szczepienia/szczepienia.github.io/issues/15#event-4638099941

--
Wysłane z aplikacji OnetPoczta

**Comment by szczepienia** [comment]
@sylwik7  Te terminy są, najłatwiej znaleźć samemu w IKP, albo naciskać na 989, żeby szukali mocniej. Lub próbować połączyć się jeszcze raz aż się trafi na bardziej ogarniętą osobę.

Może punkt trzeba wyszukiwać inaczej (po adresie, albo po nazwie)?

**Comment by sylwik7** [comment]
Hmm od wczoraj rozmawiałam  7 konsultantami, każdy twierdzi, że ten pkt im nie podał terminów i go nie widzą. Trochę boję się na ikp grzebać bo córka ma bliski termin na 17 maja w Katowicach i szkoda mi go stracić, ale wolałabym to Jaworzno ze względów logistycznych. 
Do soboty mieliśmy w okolicy styku Małopolski i Śląska dużo terminów szczególnie w Olkuszu, Oświęcimiu, Jaworznie. Od wczoraj wszystko czerwiec. Ten 17 maja to przypadkiem się znalazł. 
No nic będę cisnąć infolinię
Jedyne mnie zastanawia, że nigdzie z netu nie wynika czy ten punkt już działa. 
Pozdr😀

Dnia 10 maja 2021 10:02:53 CEST, szczepienia ***@***.***> napisał(a):
***@***.***  Te terminy są, najłatwiej znaleźć samemu w IKP, albo naciskać
>na 989, żeby szukali mocniej. Lub próbować połączyć się jeszcze raz aż
>się trafi na bardziej ogarniętą osobę.>
>>
>Może punkt trzeba wyszukiwać inaczej (po adresie, albo po nazwie)?>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/szczepienia/szczepienia.github.io/issues/15#issuecomment-836332096

--
Wysłane z aplikacji OnetPoczta

**Comment by szczepienia** [comment]
Jakby co to tutaj wspominają o tym punkcie na inwalidów wojennych 18: https://www.um.jaworzno.pl/pl/aktualnosci/6543/w_jaworznie_wkrotce_rusza_powszechne_punkty_szczepien.html

Może Pani spróbować znaleźć telefon do tej firmy: Pro4Med która organizuje ten punkt. (czasami na maila też mogą odpowiedzieć)

**Comment by szczepienia** [comment]
@sylwik7 

Proszę szukać (powiedziećna infolinii) dla takich danych:
województwo: śląskie
miasto: brak (tak brak miasta)
zakres dat: 2021-05-14  do 2021-06-10,
godziny: dowolne
szczepionka: pfizer

Wtedy na 989 znajdą te terminy.

**Comment by sylwik7** [comment]
Dzięki nim udało mi się wymusić to Jaworzno znalazłam info na wyszukiwarce o terminach w Chrzanowie czyli w zasadzie 10 km od domu. Otwierają nowy punkt, zapisałam córkę i dałam znać jeszczr wielu znajomym bo było dużo terminów na jutro i kolejne dni. 
Pozdrawiam, super projekt👍

Dnia 10 maja 2021 10:56:08 CEST, szczepienia ***@***.***> napisał(a):
>Jakby co to tutaj wspominają o tym punkcie na inwalidów wojennych 18:
>https://www.um.jaworzno.pl/pl/aktualnosci/6543/w_jaworznie_wkrotce_rusza_powszechne_punkty_szczepien.html>
>>
>Może Pani spróbować znaleźć telefon do tej firmy: Pro4Med która
>organizuje ten punkt. (czasami na maila też mogą odpowiedzieć)>
>>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/szczepienia/szczepienia.github.io/issues/15#issuecomment-836417018

--
Wysłane z aplikacji OnetPoczta
