### ISSUE TITLE
multi-select przy wyborze sczepionki

### ISSUE THREAD

**Issue by Crazytribe** [szczepienia/szczepienia.github.io#18]
Byłoby super jakby się udało zrobić multi-select szczepionki np moderna oraz Pfizer.
Po to abym mógł zobaczyć najbliższe terminy dla obydwu pasujących mi wersji szczepionki a nie tylko dla jednej.

**Comment by szczepienia** [comment]
Hej,
multiselect jest, tylko musisz naciśnać klawisz `ctrl` przy klikaniu :)
