### ISSUE TITLE
Brak J&J

### ISSUE THREAD

**Issue by misi006** [szczepienia/szczepienia.github.io#24]
Z jakiego powodu zniknęła możliwość szukania szczepionki J&J? Czy pojawi się jeszcze w przyszłości w wyszukiwarce?

**Comment by krewetka** [comment]
no opis  za wiele nie tłumaczy :) 

> Jednak J&J zniknęły szybciej o pare godzin niż myślałem, od teraz ich nie będzie na listach, pozostałe szczepionki bez zmian.

**Comment by misi006** [comment]
Stąd moje pytanie:)

**Comment by szczepienia** [comment]
Niestety system zabrał mi możliwość takiego wyszukiwania :( 
Nie sądzę, żeby się pojawiła w przyszłości, może na chwilę 9 maja - dam znać wtedy.
