### ISSUE TITLE
Dajcie zrzutke czy coś żeby wam rzucić złociszem za dobrą robotę!

### ISSUE THREAD

**Issue by greg-agacinski** [szczepienia/szczepienia.github.io#25]
Jak w tytule!

**Comment by szczepienia** [comment]
Nawet nie wiem jak takie rzeczy się rozlicza w PIT :)

**Comment by greg-agacinski** [comment]
https://www.e-pity.pl/inne-zrodla-przychodu/
> 9. Przychody nieznajdujące pokrycia w ujawnionych źródłach lub pochodzące ze źródeł nieujawnionych.

**Comment by szczepienia** [comment]
Dziękuję za sugestię, ale pracę mam (stronka nie wymaga utrzymania finansowego, tylko odrobinę mojego czasu), a ta stronka to dla mnie krótko dystansowe hobby.

Ważne, że się przydaje :)
