### ISSUE TITLE
Nr telefonu

### ISSUE THREAD

**Issue by stupitu** [szczepienia/szczepienia.github.io#26]
Tel. do Siemiatycze (podlaskie) Punkt Szczepień Powszechnych Świętojańska 25A psuje wyświetlanie kolumny z nr. telefonów

**Comment by szczepienia** [comment]
Dziękuje za informacje, już naprawiam.

**Comment by szczepienia** [comment]
Ale zaszaleli z liczbą telefonów :)

**Comment by szczepienia** [comment]
poprawiłem
