### ISSUE TITLE
[WIELKOPOLSKIE] Zły number telefonu do placówki (id=283722)

### ISSUE THREAD

**Issue by Jamar47** [szczepienia/szczepienia.github.io#29]
W tabeli pokazano pierwotny, nieaktualny numer punktu szczepień Szpitala Tymczasowego na MTP. Obecnie działa numer 616771011. Pod tym numerem działa infolinia, która jest przedziwna:  trudno osiągalna, a po szczęśliwym połączeniu odsłuchuje się muzyczkę między "Jesteś 10 w kolejce", 9, 8, 7...2, 1, 1, 1 i tu - zamiast konsultanta - komunikat: wszystkie linie zajęte i koniec połączenia... Dzisiaj zdarzyło się to 6 razy!

**Comment by szczepienia** [comment]
Dziękuję, wrzuciłem poprawkę, poprawiony numer wejdzie najpóźniej za 30 min.
