### ISSUE TITLE
Błędny numer telefonu

### ISSUE THREAD

**Issue by tomek-sztuk** [szczepienia/szczepienia.github.io#31]
Punkt Szczepień Powszechnych - Miejskie Centrum Opieki dla Osób Starszych, Przewlekle Niepełnosprawnych oraz Niesamodzielnych w Krakowie Podchorążych 3 

📞 0000000

**Comment by szczepienia** [comment]
Bardzo dziękuję za zgłoszenie, już poprawiam (co prawda do końca nie wiem jaki jest poprawny numer bo nie znalazłem na stronach, więc podam narazie do organizatora)
