### ISSUE TITLE
Dodatkowe j&j w Krakowie, potem inne miasta

### ISSUE THREAD

**Issue by migotka21** [szczepienia/szczepienia.github.io#32]
Szanowny Panie, wydaje sie, ze na j&j sa chetni. Pan tego teraz nie podaje, ale moze komus taka informacja sie przyda i da sie to upchnac. W Krk na Rynku Glownym ma byc tymczasowy punkt w namiocie na caly dlugi weekend tylko z j&j a potem ma zostac przeniesiony do innych miast w malopolsce, chociaz na razie nie podali gdzie konkretnie. Z tonu artykulu raczej wieksze miasta niz miejscowosci wykluczone, ale nie ma danych. Ma byc dla e-zarejestrowanych, czyli nie dla rejestracji tel, ale bez skierowania do tego punktu. Tak to wyglada, jakby osoby z wyznaczonymi terminami mogly przyspieszyc. Informacje sa w lokalnych gazetach i wiadomosciach ale moze ktos spoza Krk bedzie w miescie na dlugi weekend, a teraz nie ma dostepu. Pozdrawiam.

**Comment by szczepienia** [comment]
Tak wiem, ale ilość szczepionek ograniczona i już się ustawiają kolejki, na 90min przed otwarciem punktu. Raczej mało bezpieczne jeśli o mnie chodzi :(
