### ISSUE TITLE
Parametry w wyszukiwarce

### ISSUE THREAD

**Issue by tdomanski** [szczepienia/szczepienia.github.io#35]
Czy jest możliwość wpisania w adresie strony internetowej parametrów wyszukiwania (miejsowość, szczepionka) poza wyborem województwa?

**Comment by wojtekmaj** [comment]
Tak: https://szczepienia.github.io/mazowieckie?city=Warszawa&vaccine=Pfizer,Moderna

**Comment by tdomanski** [comment]
Dziękuję.
