### ISSUE TITLE
Paging a terminy

### ISSUE THREAD

**Issue by ml054** [szczepienia/szczepienia.github.io#38]
Zauwazylem ze po stronie serwera jest paging na max 60 elementow. Jesli wybiore np. szerszy zakres dat, to otrzymuje pierwszy termin np. 25 maja i 60 elementow z /find API. Po zaweżeniu zakresu dat do np. 23 mam pierwsze wolne terminy na 19. 

Pytanie zatem czy nie warto zmodyfikować wyszukiwania aby brał węższy zakres dat lub w modyfikował go na podstawie ostatniego wyszukania - czyli jesli mamy 60 itemkow to przy nastepnym uderzeniu `endDate - 1 dzien`? 

@szczepienia respect za projekt 

![RESPECT](https://media.giphy.com/media/WO5Q7FsxJN2pjYc424/giphy.gif)

**Comment by szczepienia** [comment]
Ten paging jest dziwniejszy niż się wydaje na początku, bo zwraca nawet po 100 wyników, ciężko wyczuć jak to robią.
Na przykład jak wyszukasz dla zakresu 1-8 maj, to zobaczysz jakiś termin, jak dasz 1-9 to go nie zobaczysz :)
