### ISSUE TITLE
Pytanie dot rodzaju

### ISSUE THREAD

**Issue by bdkacz** [szczepienia/szczepienia.github.io#45]
Jeżeli  28 kwietnia zapisałem się przez e-rejestrację w punkcie X na 28.05 na   pfizera , a dzis wyszukiwarka dla tych samych terminów (data,godzina)  podaje w nim J&J to mam rozumieć, że :

a)  ja dostane pfizera, a ktoś kto się dziś zapisze na fotelu obok  J&J ?
b) dostanę J&J (bo to dojedzie tam 28.05) mimo, że mam w smsie pfizera i jak chce pfizera to muszę szukać innego miejsca/terminu  (najlepiej bliższego) ?

**Comment by JabLuszko** [comment]
To nie są pytanie które powinieneś kierować tutaj. Jeśli masz jakieś wątpliwości to https://www.gov.pl/web/koronawirus/ i tam są również numery telefonów na infolinię. 

Ta strona jedynie co robi to pokazuje w bardziej przystępnej formie dane z oficjalnej strony rządowej.

A odpowiadając na pytania: Skoro się zapisałeś na X, to będziesz miał X... jeśli nic się nie zmieni (a może się zmienić, dostawy szczepionek nadal są 'kruche' - czasami przyjeżdza mniej i pewne terminy trzeba przekładać) to zostaniesz poinformowany o tym - SMSem z propozycjami i pewnie będą dzwonić.
Póki masz w systemie rządowym napisane "Dnia X na Y" to tego dnia idziesz na to co chcesz - tak, obok mogą być inne szczepionki, inne punkty - tym się zupełnie nie przejmuj.

**Comment by bdkacz** [comment]
Akurat strona rządowa to w tym wypadku słabe źródło informacji, bo rząd cały czas twierdzi, że szczepionki nie można wybrać, a wybór widoczny podczas zapisów to fatamorgana :)

Dlatego zapytałem tutaj, bo być może ktoś był w podobnej sytuacji i jest w stanie  napisać jak było w praktyce  :)

**Comment by szczepienia** [comment]
@bdkacz W punktach często szczępią różnymi szczepionkami więc dlatego możesz widzieś te same godziny dla J&J i dla Pfizera.
A to jaką Ci dadzą to kolejna sprawa :)

AZ i J&J jest mało więc mogą zamienić na Pfizera.
