### ISSUE TITLE
Problem z woj. mazowieckim

### ISSUE THREAD

**Issue by luxus83** [szczepienia/szczepienia.github.io#46]
Dzięki za świetną robotę!!! Dla woj. mazowieckiego nie filtrują się miasta oraz widać tylko dwa rodzaje szczepionek

**Comment by szczepienia** [comment]
Hej,
niestety nie znalazło więcej rodzajów szczepionek :(
Niestety nie mogę wyszukiwać dla wszystkich miejscowości więć możliwe, że gdzieś jeszcze są.
Najlepiej sprawdzać miasta w których są punkty szczepień powszechnych, bo mają największy "przemiał" i lość terminów.

**Comment by szczepienia** [comment]
@luxus83  I już widać wszystkie 4 rodzaje :)
