### ISSUE TITLE
Numery z kierunkowym +48

### ISSUE THREAD

**Issue by georgjaehnig** [szczepienia/szczepienia.github.io#49]
Świetna strona!

Czytamy też za granicą w Berlinie, dlatego proponuję dodawania +48, conajmniej do linku: `href="tel:+48..."`.

Poza tym chętnie też podaj numer do infolinii ogólnej z zagranicy: +48226262989, może jako link obok 989 (bo z 989 się nie dodzwonisz).

**Comment by konrad-gora** [comment]
Może lepiej by było gdyby numery ogólne były poza tabelką, skoro są wspólne. To pozwoliłoby zmniejszyć wysokość wierszy

**Comment by szczepienia** [comment]
Hmm, fakt.

Ale wtedy będzie to trochę dziwnie wyglądało gdy dana placówka nie występuje na https://www.gov.pl/web/szczepimysie/mapa-punktow-szczepien#/ bo nie będzie żadnego numeru.

Narazie dodam poza tabelką numery, dorzucę +48 i dodam poza tabelką numer dla zagranicy.
