### ISSUE TITLE
[MAZOWIECKIE] Zły number telefonu do placówki (id=294519)

### ISSUE THREAD

**Issue by Weinikke** [szczepienia/szczepienia.github.io#50]
Nie chorala tym bardziej potrebuje

**Comment by Weinikke** [comment]
Numer tel 884955678

**Comment by szczepienia** [comment]
Dziękuję, poprawiłem, zmiany powinny się pojawić po ok 30 - 60 min.

**Comment by Weinikke** [comment]
Closed why? Nie bylo mnie prszyznaczone zadnej daty

**Comment by Weinikke** [comment]
Dla czdgo wtedy jesc data i mozliwosci wyboru?

пт, 7 мая 2021 г., 23:48 szczepienia ***@***.***>:

**Comment by szczepienia** [comment]
Bo ta strona nie służy do rezerwacji wizyt

**Comment by Weinikke** [comment]
Wtedy nie ma byc i dat rezerwacji
Tylko danne, ale nie wybór.



пт, 7 мая 2021 г., 23:53 szczepienia ***@***.***>:
