### ISSUE TITLE
Zapytanie z J&J w parametrach

### ISSUE THREAD

**Issue by konrad-gora** [szczepienia/szczepienia.github.io#51]
Cześć,
Próbowałem robić zapytanie które od razu pokazywałoby mi dostępność szczepionki **J&J**.
Próbowałem w takich wersjach:
https://szczepienia.github.io/lubelskie?vaccine=J%20%26%20J
https://szczepienia.github.io/lubelskie?vaccine=J+%26+J
https://szczepienia.github.io/lubelskie?vaccine=J%26J
https://szczepienia.github.io/lubelskie?vaccine=J%20J
https://szczepienia.github.io/lubelskie?vaccine=J+J
https://szczepienia.github.io/lubelskie?vaccine=JJ
https://szczepienia.github.io/lubelskie?vaccine=J

Żadna z tych opcji nie zadziałała. Czy trzeba wpisać to w inny sposób czy nie ma możliwości filtrowania po J&J poprzez zapytanie?
W URL nie można wpisać po prostu J&J ponieważ & jest traktowane jako separator parametrów. %26 służy do escapeowania &

**Comment by szczepienia** [comment]
Oops, w ulru `%26`, a w html to już `&amp;`, poprawiłem.

Powinno zadziałać szukanie: https://szczepienia.github.io/lubelskie?vaccine=J+%26+J

Muszę dołożyć kiedyś automat generujący te urle.

BTW. Jak ktoś chętny to kod do UI jest otwarty a mój JavaScript jest bardzo słaby.
