### ISSUE TITLE
MAZOWIECKIE- zniknęła Warszawa 

### ISSUE THREAD

**Issue by dominikapp** [szczepienia/szczepienia.github.io#57]
W wyszukiwarce woj mazowieckie,  zniknęła Warszawa z listy miast

**Comment by szczepienia** [comment]
Niestety oznacza to, że nie znalazłem żadnego terminy dla Warszawy w najbliższych 4 tygodniach.

**Comment by dominikapp** [comment]
OK. Tak się domyśliłam, jak weszłam na gov pacjent :/ dzięki!
