### ISSUE TITLE
Wyszukiwanie po słowach kluczowych w ścieżce `&q=keyword`

### ISSUE THREAD

**Issue by lomasz** [szczepienia/szczepienia.github.io#58]
Hej,

Co myślisz o moim pomyśle:

Fajnie, że dodałeś możliwość zapisywania kryteriów wyszukiwania w URL. Może dałoby się dodać kolejny parametr, który pozwalałby przechowywać słowo kluczowe użyte w wyszukiwaniu (pole "Szukaj"), np.

```
https://szczepienia.github.io/pomorskie?city=Gdansk&q=GUMED
https://szczepienia.github.io/pomorskie?city=Gdansk&q=Dębowa+12
https://szczepienia.github.io/pomorskie?city=Gdansk&q=poniedziałek
```

?

👍 dla Was!

**Comment by szczepienia** [comment]
@lomasz Świetny pomysł, dodane: https://szczepienia.github.io/pomorskie?q=Redzi
