### ISSUE TITLE
Sortowanie.

### ISSUE THREAD

**Issue by filo4444** [szczepienia/szczepienia.github.io#59]
Witam,

w wersji desktop wiersze wyniku są sortowane od najodleglejszej daty a chyba lepiej byłoby od najwcześniejszej.

Pozdr.

**Comment by Yalpa** [comment]
+ każdy miesiąc jest sortowany(DESC) osobno

**Comment by szczepienia** [comment]
To był chyba chwilowy błąd, teraz powinno być już poprawnie.

@filo4444  Możesz potwieredzić, możliwe, że coś źle patrzę

**Comment by Yalpa** [comment]
@szczepienia wszystko gra ;)

**Comment by filo4444** [comment]
Jest OK.
