### ISSUE TITLE
Brak opcji wyszukiwania po miastach/szczepionkach

### ISSUE THREAD

**Issue by dominika-ratajczak** [szczepienia/szczepienia.github.io#60]
Cześć, 

Zauważyłam, że zniknęła dzisiaj opcja wyszukiwania wg miast i szczepionek. 

![image](https://user-images.githubusercontent.com/76884327/117256811-6bd78a00-ae4b-11eb-92c3-8e137caecf58.png)

Czy można ją przywrócić? Była bardzo pomocna. 

Dzięki!

**Comment by szczepienia** [comment]
Chwilowy błąd, już poprawione :)
