### ISSUE TITLE
Proszę podać adresy Bitcoin, ETH, LTC, DOGE. Chcemy podziękować :)

### ISSUE THREAD

**Issue by georgjaehnig** [szczepienia/szczepienia.github.io#63]
Albo podaj instytucję / jej konto, którą mamy wspierać.

**Comment by szczepienia** [comment]
Dziękuję, ale sam nie potrzebuję wsparcia finansowego, robie to jako hobby i chęci pomocy.

A instytucję myślę, że każdy może sam wybrać. Jeśli spotkało Was coś dobrego to może warto rozglądnąć się w swojej okolicy i wpłacić darowiznę instytucji/osobie która tego potrzebuję.
