### ISSUE TITLE
wolne terminy nie pokrywaja się z danymi z infolinii NFZ

### ISSUE THREAD

**Issue by gpleo72** [szczepienia/szczepienia.github.io#65]
trzykrotnie próbowałem skorzystać ze zmiany terminu szczepienia (miasto Końskie, woj świętokrzyskie). Pomimo widoczności wolnych terminów na Państwa stronie po telefonie na inforlinie NFZ okazywało się, ze takie terminy nie są wolne. Proponowane były mi inne dni, które z kolei nie były widziane na Państwa stronie. Coś tu nie działa tak jak powinno. Albo NFZ nie chce abyśmy zmieniali sobie ustalony termin szczepienia. Szkoda......

**Comment by szczepienia** [comment]
To zależy jakie to były terminy.
Pojedyncze na dany dzień znikają zbyt szybko aby było sens je umawiać.
Najlepiej patrzeć na terminy gdzie jest przynajmniej kilka (>10? zależy od miasta) terminów i jest mniejsza szansa, że się rozejdą jak ciepłe bułeczki.

Druga sprawa to infolinia - 989 korzysta z dokładnie tego samego systemu co erejestracja/IKP a tam wyszykiwanie jest ... niestabilne/dziwne.

Jeśli widziasz więcej niż jeden termin to musisz naciskać na infolinii, żeby:
- zawięzili wyszukiwanie do danego dnia na który widziałeś termin
- zawięzili zakres godzin tak aby obejmował te terminy

Często dopiero wtedy taki termin się pokaże (możesz spradzić sam na IKP jak to działa, zmiana zakresu dat powoduje, że termin nagle znika albo pojawia się).

Najlepiej dzwonić bezpośrednio do punktu, bo oni mają dane bezpośrednie bez wyszukiwania, infolinia 989 to jest ostateczność gdy jest cieżko się dodzwonić do punktu lub nie ma się konta na e-rejestracji (co jest dość proste, wystarczy pesel, nazwisko i numer telefonu).

**Comment by gpleo72** [comment]
Witam,
Dziękuję za odpowiedź. Ale właśnie taki przypadek miałem. Widoczne były cztery wolne terminy na pasujący mi dzień i miejsce. Zadzwoniłem na 989 i poporosiłem o zmianę podając dzień i miejsce. Uprzejma Pani poinformowała, że na dany dzień i w danej lokalizacji nie ma wolnych terminów. Zaproponowała inny wolny ale dużo późniejszy termin w mojej miejscowości, który nie był widoczny na Państwa stronie.
Po rozłączeniu jeszcze kilkakrotnie sprawdzałem na Państwa stronie i te wolne terminy, które mnie interesowały przez dłuższy czas były widoczne.
 
Szkoda, że to nie zadziałał. Ale przypuszczam, ze skoro nie ma takiej funkcjonalności jak zmiana terminu szczepienia na stronie e-rejestracja (po prostu zmiana a nie anulowanie i ponowne wyszukiwanie wolnego terminu) oznacza, że NFZ/GOV nie jest zainteresowany tym aby ludzie mieli taką możliwość => zarządzanie przez chaos :) lepiej im wychodzi.
 
Telefon do danego punktu szczepień nie daje możliwości oficjalnej zmiany terminu - mogą jedynie wciągnąć na swoją wewnętrzną listę oczekujących - czyli szczepienie jak jest ryzyko zniszczenia dawki. Ale tu bardziej działają znajomości, przynajmniej u nas.
 
Pozdrawiam i życzę powodzenia w innych projektach obywatelskich,
 
W dniu 2021-05-06 16:41:09 użytkownik szczepienia ***@***.***> napisał:
 
To zależy jakie to były terminy.
Pojedyncze na dany dzień znikają zbyt szybko aby było sens je umawiać.
Najlepiej patrzeć na terminy gdzie jest przynajmniej kilka (>10? zależy od miasta) terminów i jest mniejsza szansa, że się rozejdą jak ciepłe bułeczki.
Druga sprawa to infolinia - 989 korzysta z dokładnie tego samego systemu co erejestracja/IKP a tam wyszykiwanie jest ... niestabilne/dziwne.
Jeśli widziasz więcej niż jeden termin to musisz naciskać na infolinii, żeby:
zawięzili wyszukiwanie do danego dnia na który widziałeś termin
zawięzili zakres godzin tak aby obejmował te terminy
Często dopiero wtedy taki termin się pokaże (możesz spradzić sam na IKP jak to działa, zmiana zakresu dat powoduje, że termin nagle znika albo pojawia się).
Najlepiej dzwonić bezpośrednio do punktu, bo oni mają dane bezpośrednie bez wyszukiwania, infolinia 989 to jest ostateczność gdy jest cieżko się dodzwonić do punktu lub nie ma się konta na e-rejestracji (co jest dość proste, wystarczy pesel, nazwisko i numer telefonu).

**Comment by krzyk** [comment]
@gpleo72 A czy te terminy były po kolejnej aktualizacji? (tan informacja kiedy była aktualizacja jest widoczna na tabelką)

**Comment by szczepienia** [comment]
@gpleo72 A czy te terminy były po kolejnej aktualizacji? (tan informacja kiedy była aktualizacja jest widoczna na tabelką)

Co do "Telefon do danego punktu szczepień nie daje możliwości oficjalnej zmiany terminu" jest to nieprawda. Wiele razy umawiałem ludzi za pomocą telefonu do danego punktu i to jest jedna z 3 oficjalnych dróg umawiania terminów. Jeśli są dostępne terminy to jest to najpewniejsza metoda (jeśli odbierają telefony).

**Comment by gpleo72** [comment]
Tak
Były widoczne wolne terminy na dany dzień więc zadzwoniłem i Pani z infolinii ich nie widziała choć po kolejnych aktualizacjach Państwa strony nadal były widoczne. Zniknęły długo później niż dzwoniłem (myślę, że po dwóch-trzech godzinach).
Ogólnie trzy razy tak próbowałem zmienić termin, ale ten jeden przypadek zapadł mi w pamięci jako że na Państwa stronie te wolne godziny wisiały po moim telefonie na infolinię jeszcze długo.
osobiście nie mam przekonania do działania tej infolinii.
 
Co do telefonu do punktu szczepień to zapewne tak jak Pan pisze działa w większych miejscowościach. Oficjalnie NFZ/GOV podaje dwie drogi zmiany terminu: infolinia 989 lub e-rejestracja (po anulowaniu wcześniejszego terminu w ciemno).
 
Pozdrawiam,
W dniu 2021-05-07 08:31:30 użytkownik szczepienia ***@***.***> napisał:
 
@gpleo72 A czy te terminy były po kolejnej aktualizacji? (tan informacja kiedy była aktualizacja jest widoczna na tabelką)
Co do "Telefon do danego punktu szczepień nie daje możliwości oficjalnej zmiany terminu" jest to nieprawda. Wiele razy umawiałem ludzi za pomocą telefonu do danego punktu i to jest jedna z 3 oficjalnych dróg umawiania terminów. Jeśli są dostępne terminy to jest to najpewniejsza metoda (jeśli odbierają telefony).

**Comment by szczepienia** [comment]
Rozumiem problem :(, ale niestety ciężko mi na to poradzić.
Jedyne co mogę sugerować to ponowne dzwoninie na infolinię i może wtedy trafić na inną osobę która będzie inaczej wyszukiwać.

BTW. Strona https://www.gov.pl/web/szczepimysie/rejestracja podaje 3 sposoby rejestracji, ostatnim jest właśnie kontakt z danym punktem szczepień.

**Comment by gpleo72** [comment]
Witam,
Pan mówi o 3 sposobach rejestracji a tu chodzi o zmianę już ustalonego terminu szczepień.
https://samorzad.infor.pl/wiadomosci/5238815,Zmiana-terminu-szczepienia-przeciw-COVID19.html
Jak najbardziej Państwa strona pomaga osobom, które dopiero szukają najlepszego miejsca do zarejestrowania się.
Ja chciałem zmienić żeby nie trzeba było jechać i zarywać dnia pracy.  Ale zostało mi już tylko 9 dni wiec poczekam.
Ogólnie widać, że szczepionek jest już więcej niż chętnych bo np. w Kielcach są terminy od ręki a jak ja się rejestrowałem to kazali czekać 1,5 miesiąca.
Ogólnie to brawa za podjęcie tematu terminów szczepień - to powinny robić odpowiednie służby a nie pasjonaci.
I ten brak prostej funkcjonalności " zmień termin" na stronie e-rejestracji.
Pozdrawiam,
 
W dniu 2021-05-08 21:09:36 użytkownik szczepienia ***@***.***> napisał:
 
Rozumiem problem :(, ale niestety ciężko mi na to poradzić.
Jedyne co mogę sugerować to ponowne dzwoninie na infolinię i może wtedy trafić na inną osobę która będzie inaczej wyszukiwać.
BTW. Strona https://www.gov.pl/web/szczepimysie/rejestracja podaje 3 sposoby rejestracji, ostatnim jest właśnie kontakt z danym punktem szczepień.

**Comment by szczepienia** [comment]
@gpleo72 
Wprowadziłem rozwiązanie tego problemu: przycisk "Dane" (zaraz obok numeru 989 przy danym terminie) - proszę podać na infolinii parametry wyszukiwania i powinni znaleźć dany termin.
