### ISSUE TITLE
[MAZOWIECKIE] Zły region? (uuid=b54c3ff9-dda1-4a81-bbef-bae6badfbeb3)

### ISSUE THREAD

**Issue by Santanachia** [szczepienia/szczepienia.github.io#67]
Sarnaki nie są w mazowieckim(?), a w mazowieckim się wyświetlają.

**Comment by Santanachia** [comment]
a jednak są ;)

**Comment by szczepienia** [comment]
Jak zacząłem robić ta mapkę to się zdziwiełem ile jest miejscowości o tych samych nazwach, nawet w tym samym województwie :)
