### ISSUE TITLE
Terminy

### ISSUE THREAD

**Issue by TheMadMattt** [szczepienia/szczepienia.github.io#72]
Wczoraj wieczorem terminy na stronce a na rejestracji praktycznie się nie pokrywały

**Comment by szczepienia** [comment]
A rejestracją różnie bywa. A jeśli więcej ludzi naraz siądzie do rezerwacji (np. uruchomienia nowego rocznika do zapisów) to może dośc szybko zniknąć.

Warto uderzać tylko pod takie czasy gdzie jest więcej niż 10 terminów.

**Comment by szczepienia** [comment]
I warto klikać na link "Dane" (boko 989) i zmusić infolinię aby dałe takie dane wyszukiwania jak są tam podane (w szczególności zakres dat, bo od tego najczęściej zależy termin - i to nie w logiczny sposób).
