### ISSUE TITLE
[MAZOWIECKIE] Zły number telefonu do placówki (uuid=f3b8d4d2-7216-45e2-9284-8ec93a19d01a)

### ISSUE THREAD

**Issue by MariuszBakowski27** [szczepienia/szczepienia.github.io#76]
Astra not pfizer

**Comment by szczepienia** [comment]
To niestety dany punkt nie wysłał informacji o zmianie rodzaju szczepionki, albo nie dostali jednej.

**Comment by szczepienia** [comment]
Poprawiłem, miałem błąd z sortowaniem szczepionek i czasami wchodziły niepoprawne na listę. Teraz już jest dobrze.
