### ISSUE TITLE
róznica miedzy systemem a rządem

### ISSUE THREAD

**Issue by Milosz2PL** [szczepienia/szczepienia.github.io#79]
Rząd mówi ,że jest 4,5 mln wolnych terminów szczepień. Zapisanych jest około 1,5 mln, czyli na tydzień. Biorac pod uwagi kolejki to jest mało zapisów. Rząd mówi ,że jest malo chętnych a mało jest terminów. To kto kłamie?

**Comment by szczepienia** [comment]
Nikt nie kłamie (bo po co?), tutaj na mapce nie mam wszytch terminów dostępnych (przede wszystkim sprawdzam tylko na 4 tygodnie, czyli obecnie do 10 czerwca a rząd mówi o 4.5mln wolnych terminów do końca czerwca).
Również AZ sprawdzam mniej dokładnie (np. jak jest takich szczepionek więcej danego dnia, to tylko początkową listę zwracam).

No i system wyszukiwania w erejestracji jest dość kulawy, bo nie zwraca wszystkich dostepnych terminów, trzeba bardzo kombinować z parametrami, żeby znalał wszystkie terminy, a i pewnie są takie do których nie da się dostać dopóki inne nie zostaną umówione.

**Comment by szczepienia** [comment]
bo mRNA i J&J rozchodzą się jak ciepłe bułeczki :)

A jakim mieście?
