### ISSUE TITLE
Konsultanci na 989 uparcie twierdza, ze nie widza terminow widocznych na tej stronie 

### ISSUE THREAD

**Issue by carinae31585** [szczepienia/szczepienia.github.io#80]
Wykonałam już kilkanaście telefonów na 989, za każdym razem natychmiast po aktualizacji strony. Za każdym razem konsultant twierdził, że nie widzi wolnych terminów w Warszawie do czerwca, mimo że na stronie jest ich kilkadziesiąt i są nadal widoczne po kolejnych aktualizacjach. Jak to możliwe? Jak mam wyegzekwować od konsultanta znalezienie terminu podanego przez stronę?

**Comment by szczepienia** [comment]
Spróbuję (może dzisiaj, lub jutro) wrzucić taki dodatek w którym do każdego terminu będzie możliwość pokazania kryteriów wyszukiwania na potrzeby 989.

**Comment by szczepienia** [comment]
OK, dodałem przycisk "Dane" (obok numeru 989 przy każdym terminie) pod którym są parametry wyszukiwania na potrzeby IKP oraz 989.
