### ISSUE TITLE
[WIELKOPOLSKIE] Zły number telefonu do placówki (uuid=6b416e04-cd63-4164-b74b-7a5da39aee4e)

### ISSUE THREAD

**Issue by AGlowczewska** [szczepienia/szczepienia.github.io#82]
Telefon to 61 6771011 
via: https://www.skpp.edu.pl/szczepienia_na_terenie_szpitala_tymczasowego_mtp.html

**Comment by szczepienia** [comment]
Dziękuję, poprawiłem (pojawi się po następnym odświeżeniu)
