### ISSUE TITLE
[PODKARPACKIE] (uuid=c059dca7-d727-4cd5-9ea5-14044c5ef0bf)

### ISSUE THREAD

**Issue by kinkstoon** [szczepienia/szczepienia.github.io#84]
Po wyszukaniu: Pfizer, po wybraniu "Danych": Astra. Które prawidłowe?

https://user-images.githubusercontent.com/84120918/118090772-3e01c080-b3ca-11eb-98ba-ed44a06cc677.png

**Comment by szczepienia** [comment]
Już sprawdzam, widzę, ze grubszy błąd.

**Comment by szczepienia** [comment]
Między 10:10 - 10:35 powinna wejść poprawka.

Bardzo dziękuję za to zgłoszenie.

**Comment by szczepienia** [comment]
Już jest poprawka w podkarpackim. W Krośnie na Sportowej 8 na 14 maja są do wyboru: Moderna (dużo) i AZ.

Jeszcze raz bardzo dziękuję za to zgłoszenie, bez tej informacji nie odkrył bym dużego błędu.
