### ISSUE TITLE
[PODKARPACKIE] Zły number telefonu do placówki (uuid=4946ac25-d078-4942-8aa9-1137d10678e4)

### ISSUE THREAD

**Issue by Arkadiusz140496** [szczepienia/szczepienia.github.io#85]
Dzień dobry, kontaktuję się w imieniu placówki NZOZ Sokrates w Zgłobniu, przesyłam aktualny numer telefonu 
tel. 517 177 267

**Comment by szczepienia** [comment]
Dziękuję, poprawiłem
