### ISSUE TITLE
[MAZOWIECKIE, Radom] zły adres placówki

### ISSUE THREAD

**Issue by jacekz2021** [szczepienia/szczepienia.github.io#86]
Punkt drive thru w Radomiu nie ma adresu Dębowa 4.
Rzeczywista lokalizacja to parking przy cmentarzu, na drugim końcu Dębowej. Dokładne położenie (wjazd): 51.39519,21.12633
Informacja z pierwszej ręki, dzisiaj tam byłem.

Dzięki za SUPER stronkę! Pomogła mnie i wielu moim znajomym.

**Comment by szczepienia** [comment]
Super, dziękuję za informację. To pewnie wpisze adres Dębowa 23, bo jest najbliżej, i dodam lokalizację gps :)
