### ISSUE TITLE
[ŚLĄSKIE] Zła miejscowość placówki (uuid=a1b65502-cd53-415c-80e6-07f1115f1853)

### ISSUE THREAD

**Issue by matpolsl** [szczepienia/szczepienia.github.io#87]
Świetna strona!
![image](https://user-images.githubusercontent.com/56276428/118300103-ddfe3d80-b4e1-11eb-8e09-25e78c7c7846.png)
Powinno być Mysłowice zamiast Siła Mysłowice

**Comment by szczepienia** [comment]
Dzięki :), poprawiam
