### ISSUE TITLE
[MAŁOPOLSKIE] Zły number telefonu do placówki (uuid=22cd6a69-a441-40fc-b974-053a92a785ff)

### ISSUE THREAD

**Issue by LRonHubby** [szczepienia/szczepienia.github.io#88]
Brak wolnym terminów

**Comment by szczepienia** [comment]
Widocznie szybko się skończyły bo już ich nie znajduję na stronie.

**Comment by szczepienia** [comment]
Nie warto próbować gdy jest mało terminów (< 4), w dużych miastach potrafia się rozejśc w pare minut.
