### ISSUE TITLE
[MAŁOPOLSKIE] Zły number telefonu do placówki (uuid=b2a99fcf-9b97-4aee-b51f-5ad1315e2b95)

### ISSUE THREAD

**Issue by LRonHubby** [szczepienia/szczepienia.github.io#89]
Brak takiej placówki

**Comment by szczepienia** [comment]
Jest :)

Proszę poprosić 989 o wyszukanie tak jak jest pod linkiem "Dane" na stronie (jest obok numeru 989).
Nie można wyszukać po nazwie tego punktu (nie wiem dlaczego), ale pokazuje się w wynikach gdy się szuka Kraków. 15 maja do 12 czerwca (link "Dane").

A tutaj dowód z przed 5 sekund:

![image](https://user-images.githubusercontent.com/82411728/118375733-d6af6080-b5c3-11eb-852a-3c99ef5cc13f.png)
